-- Create Students table
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    attendance_number TEXT,
    class_name TEXT NOT NULL,
    parent_contact TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Transactions table
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    recipient TEXT,
    date TEXT NOT NULL,
    type TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_month TEXT,
    payment_year INTEGER,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing for performance
CREATE INDEX idx_transactions_student_id ON transactions(student_id);
CREATE INDEX idx_transactions_date ON transactions(date);
CREATE INDEX idx_students_status ON students(status);
